name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C build environment
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Install libcriterion
        run: sudo apt-get install -y libcriterion-dev

      - name: Build cnake
        run: make

      # - name: Test cnake
      #   run: make test

      - name: Clean up
        run: make clean
